echo "\n"
echo "ASCII TESTS" && ./asciitest | grep -a -n "test ko"
echo "\n"
echo "STRING TESTS" && ./stringtest | grep -a -n "test ko"
echo "\n"
echo "ADVANCED STRING TESTS" && ./advancedstringtest | grep -a -n "test ko"
echo "\n"
echo "MEM TESTS" && ./memtest | grep -a -n "test ko"
echo "\n"
echo "PRINT TESTS" && ./printtest | grep -a -n "test ko"
echo "\n"
echo "LIST TESTS" && ./listtest | grep -a -n "test ko"
echo "\n"

